### ISSUE TITLE
This project is missing a LICENSE

### ISSUE THREAD

**Issue by mik01aj** [avicndugu/phantom-theme-jekyll#2]
Hey, thanks for your, work, and I'd happily use it but it doesn't have a LICENSE file so I'm not sure if I can. Please clarify.

**Comment by avicndugu** [comment]
Thank you for bringing this to my attention.

I will add the license that came with the original HTML template. The license is [Creative Commons Attribution 3.0 Unported](http://creativecommons.org/licenses/by/3.0/)

**Comment by mik01aj** [comment]
Thanks!
